services:

  php:
    build: .docker/php
    container_name: php
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./.docker/php/msmtprc:/etc/msmtprc:ro
    environment:
      DB_HOST: mysql
      DB_NAME: database
      DB_USER: user
      DB_PASSWORD: password

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - php
      - mysql
    volumes:
      - .:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'

  mysql:
    image: mariadb:latest
    container_name: mysql
    restart: unless-stopped
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: user
      PMA_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '8080:80'

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: unless-stopped
    ports:
      - '8025:8025'
      - '1025:1025'

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'